name: 同步到 Gitee
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天北京时间午夜运行（PDT 时间晚上 8 点）
  workflow_dispatch:  # 支持手动触发
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: 修复 pip 缓存权限
        run: |
          mkdir -p /home/runner/.cache/pip
          chmod -R 775 /home/runner/.cache/pip
          echo "PIP_CACHE_DIR=/home/runner/.cache/pip" >> $GITHUB_ENV
        env:
          LANG: zh_CN.UTF-8
      - name: 配置 HTTPS 推送
        run: |
          git config --global url."https://".insteadOf git://
          git config --global url."https://gitee.com/".insteadOf git@gitee.com:
          echo "GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no" >> $GITHUB_ENV
        env:
          LANG: zh_CN.UTF-8
      - uses: Yikun/hub-mirror-action@master
        with:
          src: github/zejunxu
          dst: gitee/zejunxu
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "alist-bak"
          force_update: true
          clone_style: https
          debug: true
          timeout: "60m"
          api_timeout: "120"
        env:
          LANG: zh_CN.UTF-8
